import { repository } from "@/lib/repository"; import { conversationService } from "@/lib/services"; import { characterDirectorService } from "@/lib/character-director"; import { characterProfileHasMeaningfulContent, profileDraftForCharacter } from "@/lib/character-profile-drafts"; import type { Character, CharacterReference, CharacterReferenceMeta, GenerationDraft } from "@/lib/domain";
export async function POST(request:Request){ const body=await request.json() as {action:string;mediaId?:string;mediaIds?:string[];note?:string;conversationId?:string;text?:string;characterId?:string;characterPatch?:Partial<Character>;role?:CharacterReference["role"];canonical?:boolean;referencePatch?:Partial<Pick<CharacterReferenceMeta,"label"|"notes"|"active"|"priority"|"canonical">>&{role?:CharacterReference["role"]};draft?:GenerationDraft;collectionId?:string;name?:string;description?:string;messageId?:string;kind?:"media"|"generation";memory?:{summary:string;pinnedFacts:string;contextNotes:string};confirmCrossCharacter?:boolean;confirmed?:boolean};
 if(body.action==="character-create"&&body.name?.trim())return Response.json(repository.createCharacter(body.name,body.description??""),{status:201});
 if(body.action==="character-profile-apply-draft"&&body.characterId){const character=repository.characters().find((item)=>item.id===body.characterId);if(!character)return Response.json({error:"Active character not found."},{status:404});const current=repository.characterProfile(character.id);if(!current)return Response.json({error:"Character profile not found."},{status:404});if(characterProfileHasMeaningfulContent(character,current)&&body.confirmed!==true)return Response.json({error:"Confirmation is required before replacing existing profile content."},{status:409});const draft=profileDraftForCharacter(character);if(!draft)return Response.json({error:"No canonical assistant draft is defined for this character."},{status:404});return Response.json(repository.applyCharacterProfileDraft(character.id,draft.characterPatch,draft.profile));}
 if(body.action==="favorite"&&body.mediaId){const asset=repository.toggleFavorite(body.mediaId);characterDirectorService.rememberFavorite(body.mediaId);return Response.json(asset);} if(body.action==="reference"&&body.mediaId) return Response.json(repository.setReference(body.mediaId)); if(body.action==="note"&&body.mediaId){repository.setNote(body.mediaId,body.note??"");characterDirectorService.rememberNote(body.mediaId,body.note??"");return Response.json({ok:true});}
 if(body.action==="character-update"&&body.characterId) return Response.json(repository.updateCharacter(body.characterId,body.characterPatch??{}));
 if(body.action==="character-reference-add"&&body.characterId&&body.mediaId){const asset=repository.asset(body.mediaId);if(!asset)return Response.json({error:"Media not found."},{status:404});if(asset.characterId!==body.characterId&&!body.confirmCrossCharacter)return Response.json({error:"Confirm adding media from another character."},{status:409});repository.addCharacterReference(body.characterId,body.mediaId,body.role??"face",body.canonical??false);repository.setReference(body.mediaId);return Response.json({references:repository.characterReferences(body.characterId)});}
 if(body.action==="character-reference-bulk"&&body.characterId&&body.mediaIds?.length&&body.referencePatch){const refs=repository.characterReferences(body.characterId);for(const id of body.mediaIds){const ref=refs.find((item)=>item.mediaId===id);if(ref&&body.referencePatch.role&&body.referencePatch.role!==ref.role){repository.removeCharacterReference(body.characterId,id,ref.role);repository.addCharacterReference(body.characterId,id,body.referencePatch.role,body.referencePatch.canonical??ref.canonical);repository.updateCharacterReference(body.characterId,id,body.referencePatch.role,{label:body.referencePatch.label??ref.label,notes:body.referencePatch.notes??ref.notes,active:body.referencePatch.active??ref.active,priority:body.referencePatch.priority??ref.priority,canonical:body.referencePatch.canonical??ref.canonical});}else if(ref)repository.updateCharacterReference(body.characterId,id,ref.role,body.referencePatch);else if(body.referencePatch.role)repository.addCharacterReference(body.characterId,id,body.referencePatch.role,body.referencePatch.canonical??false);}return Response.json({references:repository.characterReferences(body.characterId)});}
 if(body.action==="character-reference-add-existing"&&body.characterId&&body.mediaId){const asset=repository.asset(body.mediaId);if(!asset)return Response.json({error:"Media not found."},{status:404});if(asset.characterId!==body.characterId&&!body.confirmCrossCharacter)return Response.json({error:"Confirm adding media from another character."},{status:409});repository.addCharacterReference(body.characterId,body.mediaId,body.role??"face",body.canonical??false);repository.setReference(body.mediaId);return Response.json({ok:true,references:repository.characterReferences(body.characterId)});}
 if(body.action==="character-set-portrait"&&body.characterId&&body.mediaId){const asset=repository.asset(body.mediaId);const ref=repository.characterReferences(body.characterId).find((item)=>item.mediaId===body.mediaId);if(!asset||!ref)return Response.json({error:"Choose an image reference in this character's Vault."},{status:400});if(asset.type!=="image")return Response.json({error:"Only image references can be a character portrait."},{status:400});return Response.json(repository.updateCharacter(body.characterId,{portraitUrl:asset.url}));}
 if(body.action==="character-reference-update"&&body.characterId&&body.mediaId&&body.role) return Response.json(repository.updateCharacterReference(body.characterId,body.mediaId,body.role,body.referencePatch??{}));
 if(body.action==="character-reference-remove"&&body.characterId&&body.mediaId&&body.role){repository.removeCharacterReference(body.characterId,body.mediaId,body.role);return Response.json({ok:true});}
 if(body.action==="draft-save"&&body.draft){repository.saveDraft(body.draft);return Response.json(repository.draft(body.draft.id));} if(body.action==="draft-clear"){repository.clearDraft();return Response.json({ok:true});}
 if(body.action==="collection-create"&&body.name)return Response.json(repository.createCollection(body.name)); if(body.action==="collection-rename"&&body.collectionId&&body.name){repository.renameCollection(body.collectionId,body.name);return Response.json({ok:true});} if(body.action==="collection-add"&&body.collectionId&&body.mediaId){repository.addToCollection(body.collectionId,body.mediaId);return Response.json({ok:true});}if(body.action==="collection-remove"&&body.collectionId&&body.mediaId){repository.removeFromCollection(body.collectionId,body.mediaId);return Response.json({ok:true});}
 if(body.action==="memory-save"&&body.conversationId&&body.memory){repository.saveMemory({conversationId:body.conversationId,...body.memory,updatedAt:new Date().toISOString()});return Response.json(repository.memory(body.conversationId)[0]);}
 if(body.action==="message-attach"&&body.messageId&&body.mediaId){repository.attachMessage(body.messageId,body.mediaId,body.kind);return Response.json({ok:true});}
 if(body.action==="message"&&body.conversationId&&body.text){ const conversation=repository.conversations().find(c=>c.id===body.conversationId); if(!conversation)return Response.json({error:"Conversation missing"},{status:404}); const character=repository.character(conversation.characterId); const recent=repository.messages(body.conversationId).slice(-6).map(m=>m.body); const userMessage=repository.addMessage(body.conversationId,"user",body.text);if(body.mediaId)repository.attachMessage(userMessage.id,body.mediaId,"media"); const characterMessage=repository.addMessage(body.conversationId,"character",conversationService.reply(character,body.text,recent)); return Response.json({messages:repository.messages(body.conversationId),userMessage,characterMessage}); } return Response.json({error:"Unsupported action"},{status:400}); }
