import { repository } from "@/lib/repository"; import { conversationService } from "@/lib/services"; import type { Character, CharacterReference, GenerationDraft } from "@/lib/domain";
export async function POST(request:Request){ const body=await request.json() as {action:string;mediaId?:string;note?:string;conversationId?:string;text?:string;characterId?:string;characterPatch?:Partial<Character>;role?:CharacterReference["role"];canonical?:boolean;referencePatch?:{label?:string;notes?:string;active?:boolean;priority?:number;canonical?:boolean};draft?:GenerationDraft;collectionId?:string;name?:string;messageId?:string;kind?:"media"|"generation";memory?:{summary:string;pinnedFacts:string;contextNotes:string}};
 if(body.action==="favorite"&&body.mediaId) return Response.json(repository.toggleFavorite(body.mediaId)); if(body.action==="reference"&&body.mediaId) return Response.json(repository.setReference(body.mediaId)); if(body.action==="note"&&body.mediaId){repository.setNote(body.mediaId,body.note??"");return Response.json({ok:true});}
 if(body.action==="character-update"&&body.characterId) return Response.json(repository.updateCharacter(body.characterId,body.characterPatch??{}));
 if(body.action==="character-reference-add"&&body.characterId&&body.mediaId){repository.addCharacterReference(body.characterId,body.mediaId,body.role??"face",body.canonical??true);return Response.json({references:repository.characterReferences(body.characterId)});}
 if(body.action==="character-reference-update"&&body.characterId&&body.mediaId&&body.role) return Response.json(repository.updateCharacterReference(body.characterId,body.mediaId,body.role,body.referencePatch??{}));
 if(body.action==="character-reference-remove"&&body.characterId&&body.mediaId&&body.role){repository.removeCharacterReference(body.characterId,body.mediaId,body.role);return Response.json({ok:true});}
 if(body.action==="draft-save"&&body.draft){repository.saveDraft(body.draft);return Response.json(repository.draft(body.draft.id));} if(body.action==="draft-clear"){repository.clearDraft();return Response.json({ok:true});}
 if(body.action==="collection-create"&&body.name)return Response.json(repository.createCollection(body.name)); if(body.action==="collection-rename"&&body.collectionId&&body.name){repository.renameCollection(body.collectionId,body.name);return Response.json({ok:true});} if(body.action==="collection-add"&&body.collectionId&&body.mediaId){repository.addToCollection(body.collectionId,body.mediaId);return Response.json({ok:true});}if(body.action==="collection-remove"&&body.collectionId&&body.mediaId){repository.removeFromCollection(body.collectionId,body.mediaId);return Response.json({ok:true});}
 if(body.action==="memory-save"&&body.conversationId&&body.memory){repository.saveMemory({conversationId:body.conversationId,...body.memory,updatedAt:new Date().toISOString()});return Response.json(repository.memory(body.conversationId)[0]);}
 if(body.action==="message-attach"&&body.messageId&&body.mediaId){repository.attachMessage(body.messageId,body.mediaId,body.kind);return Response.json({ok:true});}
 if(body.action==="message"&&body.conversationId&&body.text){ const conversation=repository.conversations().find(c=>c.id===body.conversationId); if(!conversation)return Response.json({error:"Conversation missing"},{status:404}); const character=repository.character(conversation.characterId); const recent=repository.messages(body.conversationId).slice(-6).map(m=>m.body); const userMessage=repository.addMessage(body.conversationId,"user",body.text);if(body.mediaId)repository.attachMessage(userMessage.id,body.mediaId,"media"); const characterMessage=repository.addMessage(body.conversationId,"character",conversationService.reply(character,body.text,recent)); return Response.json({messages:repository.messages(body.conversationId),userMessage,characterMessage}); } return Response.json({error:"Unsupported action"},{status:400}); }
