import { describe,expect,it } from "vitest";
import { HotApiClient,MuApiClient,MockProviderAssetPublisher,deployments,normalizeError,resolve } from "../lib/live-contracts";
const image={id:"img",url:"https://assets.example/a.png",kind:"image" as const,role:"subject" as const}; const video={id:"vid",url:"https://assets.example/a.mp4",kind:"video" as const,role:"motion" as const};const audio={id:"aud",url:"https://assets.example/a.mp3",kind:"audio" as const,role:"audio-mood" as const};
describe("verified gateway dry-run contracts",()=>{
 it("maps HotAPI Seedream text and multi-image edit",()=>{const text=resolve({family:"seedream-5.0-pro",mode:"text",prompt:"x",references:[],resolution:"4K"}).find(x=>x.deployment.id==="hotapi-seedream-t2i")!;expect(text.compatible).toBe(true);expect(text.payload.size).toBe("4K");const edit=resolve({family:"seedream-5.0-pro",mode:"edit",prompt:"x",references:[image,image]}).find(x=>x.deployment.id==="hotapi-seedream-edit")!;expect(edit.compatible).toBe(true);expect(Array.isArray(edit.payload.image)).toBe(true);});
 it("rejects unsupported HotAPI reference video while routing Omni",()=>{const results=resolve({family:"seedance-2.5",mode:"reference",prompt:"x",references:[image,video,audio],duration:5,resolution:"720p"});expect(results.find(x=>x.deployment.id==="hotapi-seedance-reference")?.compatible).toBe(false);expect(results.find(x=>x.deployment.id==="muapi-seedance-omni")?.compatible).toBe(true);});
 it("enforces MuAPI documented multimodal limits",()=>{const refs=[...Array.from({length:30},(_,i)=>({...image,id:`i${i}`})),...Array.from({length:10},(_,i)=>({...video,id:`v${i}`})),...Array.from({length:10},(_,i)=>({...audio,id:`a${i}`}))];const ok=resolve({family:"seedance-2.5",mode:"reference",prompt:"x",references:refs,duration:30,resolution:"4k"}).find(x=>x.deployment.id==="muapi-seedance-omni")!;expect(ok.compatible).toBe(true);const excessive=resolve({family:"seedance-2.5",mode:"reference",prompt:"x",references:[...refs,image],duration:30,resolution:"4k"}).find(x=>x.deployment.id==="muapi-seedance-omni")!;expect(excessive.compatible).toBe(false);});
 it("never sends network traffic in dry-run",async()=>{let calls=0;const transport={request:async()=>{calls++;return {status:202,json:{}}}};const preview=resolve({family:"seedance-2.5",mode:"reference",prompt:"x",references:[image,video,audio],duration:5,resolution:"720p"}).find(x=>x.deployment.id==="muapi-seedance-omni")!;const result=await new MuApiClient(transport,undefined,true).submit(preview);expect((result as {dryRun:boolean}).dryRun).toBe(true);expect(calls).toBe(0);});
 it("supports publisher abstraction and normalized errors",async()=>{expect((await new MockProviderAssetPublisher().publish(image)).providerUrl).toContain("publisher.invalid");expect(normalizeError("rate_limit_error")).toBe("rate_limited");expect(normalizeError("unknown")).toBe("unknown_provider_error");expect(deployments.filter(x=>x.provider==="MuAPI")).toHaveLength(1);});
});
