export type MediaType = "image" | "video";
export type JobStatus = "queued" | "generating" | "finalizing" | "completed" | "failed" | "cancelled";
export type GenerationMode = "image" | "video";
export type InitiativeLevel = "REACTIVE" | "CREATIVE" | "DIRECTOR";
export type SceneProposalStatus = "DRAFT" | "PROPOSED" | "SAVED" | "ACCEPTED" | "REJECTED" | "REMIXED" | "GENERATED";

export interface ProviderCapabilities {
  providerId: string; label: string; mode: GenerationMode;
  textPrompt: boolean; negativePrompt: boolean; referenceImages: boolean; referenceVideos: boolean;
  multipleReferences: boolean; imageToImage: boolean; imageToVideo: boolean; videoReference: boolean;
  aspectRatios: string[]; resolutions: string[]; durations: number[]; seed: boolean;
  guidance: boolean; generationCount: boolean; audio: boolean; advancedControls: string[];
}

export interface Character { id: string; name: string; handle: string; portraitUrl: string; description: string; personality: string; identityNotes: string; defaultsJson: string; createdAt: string; }
export interface CreativeProfile { favoriteEnvironments:string[]; wardrobeCategories:string[]; preferredLighting:string[]; preferredMoods:string[]; preferredShotTypes:string[]; cameraEnergy:string[]; mediaBalance:"image"|"video"|"balanced"; experimentationLevel:number; visualThemes:string[]; avoidedThemes:string[]; ideasToTry:string[]; ideasTiredOf:string[]; creativeBoldness:number; noveltyPreference:number; repetitionTolerance:number; }
export interface CharacterProfile { characterId:string; initiativeLevel:InitiativeLevel; adultCharacter:boolean; ageVerifiedAdult:boolean; conversationalProfile:{speakingStyle:string;vocabulary:string[];confidence:number;humorStyle:string;emotionalExpressiveness:number;attitude:string;boundaries:string[];lore:string;relationshipNotes:string}; creativeProfile:CreativeProfile; updatedAt:string; }
export interface MediaAsset { id: string; characterId: string; type: MediaType; url: string; posterUrl: string | null; title: string; caption: string; prompt: string; providerId: string; settingsJson: string; parentId: string | null; isReference: boolean; createdAt: string; favorite: boolean; }
export interface GenerationJob { id: string; characterId: string; mode: GenerationMode; prompt: string; status: JobStatus; providerId: string; settingsJson: string; parentMediaId: string | null; conversationId: string | null; createdAt: string; updatedAt: string; error: string | null; mediaId: string | null; }
export interface Conversation { id: string; characterId: string; updatedAt: string; unread: boolean; }
export interface Message { id: string; conversationId: string; role: "user" | "character"; body: string; createdAt: string; }
export interface CharacterReference { characterId: string; mediaId: string; role: "face"|"body"|"hair"|"look"|"outfit"|"environment"|"pose"|"motion"|"video"|"other"; canonical: boolean; createdAt: string; }
export interface JobReference { jobId: string; mediaId: string; role: "canonical"|"scene"|"parent"|"video"; position: number; }
export interface CharacterReferenceMeta extends CharacterReference { label:string; notes:string; active:boolean; priority:number; }
export interface GenerationDraft { id:string; characterId:string; mode:GenerationMode; payloadJson:string; updatedAt:string; }
export interface UsageEntry { id:string; jobId:string; providerId:string; model:string; mediaType:MediaType; estimatedCost:number; actualCost:number|null; usageJson:string; createdAt:string; }
export interface ConversationMemory { conversationId:string; summary:string; pinnedFacts:string; contextNotes:string; updatedAt:string; }
export interface RecentCreativeScene { mediaId:string; proposalId?:string; location?:string; wardrobe?:string; lighting?:string; mood?:string; shotType?:string; cameraDirection?:string; referenceIds?:string[]; title?:string; }
export interface CreativeMemory { characterId:string; recentSceneIds:string[]; recentScenes:RecentCreativeScene[]; recentLocations:string[]; recentWardrobes:string[]; recentLightings:string[]; recentMoods:string[]; recentShotTypes:string[]; recentCameraDirections:string[]; recentReferencePacks:string[][]; savedProposalIds:string[]; acceptedProposalIds:string[]; rejectedProposalIds:string[]; remixedProposalIds:string[]; generatedProposalIds:string[]; favoriteMediaIds:string[]; resultNotes:Record<string,string>; updatedAt:string; }
export interface ProposalReference { proposalId:string; mediaId:string; role:CharacterReference["role"]; position:number; }
export interface SceneProposal { id:string; parentProposalId:string|null; characterId:string; conversationId:string; title:string; naturalLanguagePitch:string; concept:string; location:string; wardrobe:string; mood:string; lighting:string; shotDescription:string; cameraDirection:string; imageOrVideoIntent:GenerationMode; suggestedAspectRatio:string; suggestedDuration:number|null; suggestedReferenceIds:string[]; suggestedReferenceRoles:Record<string,CharacterReference["role"]>; proposedImagePlan:string; proposedVideoPlan:string; noveltyReason:string; sourceMessageIds:string[]; status:SceneProposalStatus; proposalSource:"conversation"|"proactive"|"remix"; noveltyScore:number; similarityScore:number; createdAt:string; updatedAt:string; }
export interface ConversationSummary { conversationId:string; summary:string; summarizedThroughMessageId:string|null; summarizedAt:string|null; pinnedFacts:string[]; recentUnsummarizedMessageIds:string[]; }
export interface PinnedMemory { id:string; conversationId:string; category:string; body:string; createdAt:string; }
export interface InitiativeState { characterId:string; lastEvaluatedAt:string|null; nextEligibleAt:string|null; lastProactiveProposalAt:string|null; dailyCount:number; dailyCountDate:string|null; cooldownSeconds:number; maxPerDay:number; }
export type AdultRoleplayCapability="supported"|"not_supported"|"not_evaluated";
export interface ConversationProviderDeployment { providerId:string; model:string; connected:boolean; textConversation:boolean; structuredOutput:boolean; contextWindow:number|null; streaming:boolean; toolCalling:boolean; adultRoleplay:AdultRoleplayCapability; estimatedInputCostPerMillion:number|null; estimatedOutputCostPerMillion:number|null; }
export interface ChatUsageEntry { id:string; providerId:string; model:string; characterId:string; conversationId:string; inputTokens:number; outputTokens:number; estimatedCost:number; actualCost:number|null; createdAt:string; }
export interface MediaReaction { mediaId:string; proposalId:string|null; characterId:string; messageId:string; payloadJson:string; createdAt:string; }
export interface NoveltySignal { noveltyScore:number; similarityScore:number; similarDimensions:string[]; repeatedConcept:boolean; }
export interface CharacterBrainResponse { message:string; intent:"conversation"|"scene_proposal"|"scene_revision"; sceneProposal?:Partial<SceneProposal>; memoryCandidates:string[]; creativeSignals:Record<string,string|number|boolean>; }
export interface CharacterBrainContext { character:Character; profile:CharacterProfile; conversationId:string; conversationSummary:ConversationSummary; recentMessages:Message[]; recentUnsummarizedMessages:Message[]; pinnedMemories:PinnedMemory[]; creativeMemory:CreativeMemory; recentCreativeHistory:RecentCreativeScene[]; visualIdentity:{identityNotes:string;generationDefaults:Record<string,unknown>;canonicalReferences:CharacterReferenceMeta[]}; limits:{recentMessages:number;pinnedMemories:number;recentScenes:number;summaryCharacters:number;messageCharacters:number;pinnedMemoryCharacters:number}; }
export interface MessageAttachment { messageId:string; mediaId:string; kind:"media"|"generation"; }
export interface JobEvent { id:string; jobId:string; channel:"poll"|"callback"; state:JobStatus; message:string; createdAt:string; }
export interface AppSnapshot { characters: Character[]; media: MediaAsset[]; jobs: GenerationJob[]; conversations: Conversation[]; messages: Message[]; collections: { id: string; name: string; mediaIds: string[] }[]; notes: Record<string, string>; characterReferences: CharacterReferenceMeta[]; jobReferences: JobReference[]; capabilities: ProviderCapabilities[]; drafts:GenerationDraft[]; ledger:UsageEntry[]; memory:ConversationMemory[]; attachments:MessageAttachment[]; events:JobEvent[]; characterProfiles:CharacterProfile[]; creativeMemories:CreativeMemory[]; proposals:SceneProposal[]; proposalReferences:ProposalReference[]; conversationSummaries:ConversationSummary[]; pinnedMemories:PinnedMemory[]; initiativeStates:InitiativeState[]; conversationProviders:ConversationProviderDeployment[]; chatUsage:ChatUsageEntry[]; mediaReactions:MediaReaction[]; }

export interface GenerationInput { characterId: string; mode: GenerationMode; prompt: string; aspectRatio: string; preset: string; count?: number; duration?: number; simulation?: "success" | "failure" | "timeout"; parentMediaId?: string | null; conversationId?: string | null; referenceAssetIds?: string[]; referenceAssetRoles?:Record<string,CharacterReference["role"]>; proposalId?:string|null; sceneContext?:Partial<Pick<SceneProposal,"concept"|"location"|"wardrobe"|"mood"|"lighting"|"shotDescription"|"cameraDirection"|"proposedImagePlan"|"proposedVideoPlan">>; negativePrompt?: string; seed?: string; audio?: boolean; }
export interface ProviderRequest { job: GenerationJob; character: Character; input: GenerationInput; }
export interface ProviderResult { providerJobId?:string; state: JobStatus; progress?:number; statusMessage?:string; asset?: Omit<MediaAsset, "favorite">; outputs?: {mimeType:string;type:MediaType;url?:string}[]; providerMetadata?:Record<string,unknown>; usage?:{estimatedCost:number;actualCost?:number;units?:number}; error?: string; errorCode?:string; retryable?:boolean; }
export interface ImageGenerationProvider { readonly id: string; advance(request: ProviderRequest, elapsedMs: number): ProviderResult; }
export interface VideoGenerationProvider { readonly id: string; advance(request: ProviderRequest, elapsedMs: number): ProviderResult; }
