import { createHash,randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import fs from "node:fs";import path from "node:path";
import { db } from "./db";
export type LivePlan={provider:"HotAPI"|"MuAPI";deployment:string;request:unknown;estimate:number;videoReferenceSeconds?:number};
const now=()=>new Date().toISOString(); const vaultPath=path.join(process.cwd(),"data","provider-secrets.json");
export class WindowsDpapiVault{private run(mode:"protect"|"unprotect",value:string){const script=`$b=[Convert]::FromBase64String($env:FLEX_SCENE_SECRET);$s=[Security.Cryptography.DataProtectionScope]::CurrentUser;if('${mode}' -eq 'protect'){$o=[Security.Cryptography.ProtectedData]::Protect($b,$null,$s)}else{$o=[Security.Cryptography.ProtectedData]::Unprotect($b,$null,$s)};[Convert]::ToBase64String($o)`;const out=spawnSync("powershell.exe",["-NoProfile","-NonInteractive","-Command",script],{env:{...process.env,FLEX_SCENE_SECRET:Buffer.from(value).toString("base64")}});if(out.status!==0)throw new Error("Windows DPAPI operation failed.");return out.stdout.toString().trim();} store(provider:string,secret:string){fs.mkdirSync(path.dirname(vaultPath),{recursive:true});const existing=fs.existsSync(vaultPath)?JSON.parse(fs.readFileSync(vaultPath,"utf8")):{};existing[provider]=this.run("protect",secret);fs.writeFileSync(vaultPath,JSON.stringify(existing));} read(provider:string){const data=fs.existsSync(vaultPath)?JSON.parse(fs.readFileSync(vaultPath,"utf8")):{};return data[provider]?this.run("unprotect",Buffer.from(data[provider],"base64").toString()):undefined;} fingerprint(provider:string){const secret=this.read(provider);return secret?`••••${createHash("sha256").update(secret).digest("hex").slice(-4).toUpperCase()}`:undefined;}}
export const vault=new WindowsDpapiVault();
export class GenerationCostGovernor{settings(provider:string){let row=db.prepare("SELECT * FROM providerSettings WHERE provider=?").get(provider) as {provider:string;enabled:number;freeze:number;dailyCap:number;monthlyCap:number;perGenerationCap:number}|undefined;if(!row){db.prepare("INSERT INTO providerSettings VALUES(?,?,?,?,?,?,?)").run(provider,0,0,1,5,.25,now());row=db.prepare("SELECT * FROM providerSettings WHERE provider=?").get(provider) as typeof row;}return row!;} set(provider:string,patch:{enabled?:boolean;freeze?:boolean;dailyCap?:number;monthlyCap?:number;perGenerationCap?:number}){const s={...this.settings(provider),...patch};db.prepare("UPDATE providerSettings SET enabled=?,freeze=?,dailyCap=?,monthlyCap=?,perGenerationCap=?,updatedAt=? WHERE provider=?").run(Number(s.enabled),Number(s.freeze),s.dailyCap,s.monthlyCap,s.perGenerationCap,now(),provider);audit(patch.freeze?"freeze-changed":"provider-settings",{provider,patch});return this.settings(provider);} authorize(plan:LivePlan){const s=this.settings(plan.provider);if(!s.enabled)throw new Error("LIVE_PROVIDERS_DISABLED");if(s.freeze)throw new Error("PAID_GENERATION_FROZEN");if(plan.estimate>s.perGenerationCap)throw new Error("PER_GENERATION_CAP");const spend=this.spend(plan.provider);if(spend.today+plan.estimate>s.dailyCap)throw new Error("DAILY_CAP");if(spend.month+plan.estimate>s.monthlyCap)throw new Error("MONTHLY_CAP");const hash=createHash("sha256").update(JSON.stringify(plan.request)).digest("hex");const id=randomUUID();db.prepare("INSERT INTO liveAuthorizations VALUES(?,?,?,?,?,?,?)").run(id,plan.provider,plan.deployment,hash,plan.estimate,new Date(Date.now()+10*60_000).toISOString(),null);audit("authorized",{id,provider:plan.provider,deployment:plan.deployment,estimate:plan.estimate});return {id,hash,maxCost:plan.estimate};} consume(id:string,plan:LivePlan){const row=db.prepare("SELECT * FROM liveAuthorizations WHERE id=?").get(id) as {requestHash:string;consumedAt:string|null;expiresAt:string;maxCost:number}|undefined;const hash=createHash("sha256").update(JSON.stringify(plan.request)).digest("hex");if(!row||row.consumedAt||row.expiresAt<now()||row.requestHash!==hash||plan.estimate>row.maxCost)throw new Error("INVALID_OR_CONSUMED_AUTHORIZATION");db.prepare("UPDATE liveAuthorizations SET consumedAt=? WHERE id=?").run(now(),id);audit("authorization-consumed",{id});} spend(provider:string){const rows=db.prepare("SELECT estimatedCost,createdAt FROM usageLedger WHERE providerId=?").all(provider) as {estimatedCost:number;createdAt:string}[];const d=new Date();const today=rows.filter(r=>new Date(r.createdAt).toDateString()===d.toDateString()).reduce((x,r)=>x+r.estimatedCost,0);const month=rows.filter(r=>new Date(r.createdAt).getMonth()===d.getMonth()&&new Date(r.createdAt).getFullYear()===d.getFullYear()).reduce((x,r)=>x+r.estimatedCost,0);return {today,month};}}
export const governor=new GenerationCostGovernor();export function audit(event:string,detail:unknown){db.prepare("INSERT INTO activationAudit VALUES(?,?,?,?)").run(randomUUID(),event,JSON.stringify(detail),now());}
