/** Offline-only, verified gateway contract layer. Never submits while DRY_RUN_PROVIDER_MODE is true. */
export type ReferenceKind="image"|"video"|"audio";
export type ReferenceRole="subject"|"face"|"body"|"wardrobe"|"environment"|"composition"|"style"|"motion"|"camera"|"audio-mood"|"opening-frame"|"ending-frame"|"source-video"|"generic";
export type LiveRequest={family:"seedream-5.0-pro"|"seedance-2.5";mode:"text"|"image"|"reference"|"edit"|"extend";prompt:string;references:{id:string;url:string;kind:ReferenceKind;role:ReferenceRole}[];aspectRatio?:string;resolution?:string;duration?:number;audio?:boolean;seed?:number;};
export type Deployment={id:string;provider:"HotAPI"|"MuAPI";family:LiveRequest["family"];label:string;path:string;imageMax:number;videoMax:number;audioMax:number;durations:number[];resolutions:string[];modes:LiveRequest["mode"][];estimatedUsd?:number;connection:"not-connected"};
export const deployments:Deployment[]=[
 {id:"hotapi-seedream-t2i",provider:"HotAPI",family:"seedream-5.0-pro",label:"Seedream 5.0 Pro Spicy · Text",path:"/v1/seedream-5.0-pro-spicy/text-to-image",imageMax:0,videoMax:0,audioMax:0,durations:[],resolutions:["2K","3K","4K"],modes:["text"],estimatedUsd:.12,connection:"not-connected"},
 {id:"hotapi-seedream-edit",provider:"HotAPI",family:"seedream-5.0-pro",label:"Seedream 5.0 Pro Spicy · Image Edit",path:"/v1/seedream-5.0-pro-spicy/image-edit",imageMax:14,videoMax:0,audioMax:0,durations:[],resolutions:["2K","3K","4K"],modes:["image","reference","edit"],estimatedUsd:.12,connection:"not-connected"},
 {id:"hotapi-seedance-text",provider:"HotAPI",family:"seedance-2.5",label:"Seedance 2.5 Spicy · Text to Video",path:"/v1/seedance-2.5-spicy/text-to-video",imageMax:0,videoMax:0,audioMax:0,durations:[4,5,10,15,20,25,30],resolutions:["480p","720p"],modes:["text"],connection:"not-connected"},
 {id:"hotapi-seedance-image",provider:"HotAPI",family:"seedance-2.5",label:"Seedance 2.5 Spicy · Image to Video",path:"/v1/seedance-2.5-spicy/image-to-video",imageMax:2,videoMax:0,audioMax:0,durations:[4,5,10,15,20,25,30],resolutions:["480p","720p"],modes:["image"],connection:"not-connected"},
 {id:"hotapi-seedance-reference",provider:"HotAPI",family:"seedance-2.5",label:"Seedance 2.5 Spicy · Image/Audio Reference",path:"/v1/seedance-2.5-spicy/reference-to-video",imageMax:30,videoMax:0,audioMax:10,durations:[4,5,10,15,20,25,30],resolutions:["480p","720p"],modes:["reference"],connection:"not-connected"},
 {id:"muapi-seedance-omni",provider:"MuAPI",family:"seedance-2.5",label:"Seedance 2.5 Spicy · Omni Reference",path:"/api/v1/seedance-2.5-spicy-omni-reference",imageMax:30,videoMax:10,audioMax:10,durations:[5,10,15,20,25,30],resolutions:["480p","720p","1080p","4k"],modes:["text","image","reference","edit","extend"],connection:"not-connected"}
];
export type Preview={deployment:Deployment;compatible:boolean;reasons:string[];endpoint:string;payload:Record<string,unknown>;requiresPublishing:boolean;estimatedUsd?:number};
const count=(r:LiveRequest,k:ReferenceKind)=>r.references.filter(x=>x.kind===k);
export function resolve(request:LiveRequest){return deployments.filter(d=>d.family===request.family).map(d=>{const reasons:string[]=[];const images=count(request,"image"),videos=count(request,"video"),audios=count(request,"audio");if(!d.modes.includes(request.mode))reasons.push("Workflow mode unsupported");if(images.length>d.imageMax)reasons.push(`Image references exceed ${d.imageMax}`);if(videos.length>d.videoMax)reasons.push(videos.length?`Reference video unsupported or exceeds ${d.videoMax}`:"Video references unsupported");if(audios.length>d.audioMax)reasons.push(`Audio references exceed ${d.audioMax}`);if(request.duration&&!d.durations.includes(request.duration))reasons.push("Duration unsupported");if(request.resolution&&!d.resolutions.includes(request.resolution))reasons.push("Resolution unsupported");return buildPreview(d,request,reasons);});}
function buildPreview(d:Deployment,r:LiveRequest,reasons:string[]):Preview{const images=count(r,"image").map(x=>x.url),videos=count(r,"video").map(x=>x.url),audios=count(r,"audio").map(x=>x.url);let payload:Record<string,unknown>={prompt:r.prompt};if(d.provider==="HotAPI"){if(d.family==="seedream-5.0-pro"){Object.assign(payload,{size:r.resolution,aspect_ratio:r.aspectRatio});if(images.length)payload.image=images.length===1?images[0]:images;}else Object.assign(payload,{duration_seconds:r.duration,resolution:r.resolution,ratio:r.aspectRatio,generate_audio:r.audio, ...(images.length?{image:images[0],last_frame:images[1]}:{}), ...(d.id.includes("reference")?{images,audio_urls:audios}:{})});}else Object.assign(payload,{prompt:r.prompt,images_list:images,videos_list:videos,audios_list:audios,resolution:r.resolution,duration:r.duration,aspect_ratio:r.aspectRatio,seed:r.seed,omni_reference_task_type:r.mode==="edit"?"edit":r.mode==="extend"?"extend":"auto"});return {deployment:d,compatible:!reasons.length,reasons,endpoint:`https://${d.provider==="HotAPI"?"api.hotapi.ai":"api.muapi.ai"}${d.path}`,payload,requiresPublishing:r.references.length>0,estimatedUsd:d.estimatedUsd};}
export interface HttpTransport{request(input:{url:string;method:string;headers:Record<string,string>;body?:string}):Promise<{status:number;json:unknown}>}
export class HotApiClient{constructor(private transport:HttpTransport,private key?:string,private dryRun=true){} async submit(preview:Preview){if(this.dryRun)return {dryRun:true,preview};return this.transport.request({url:preview.endpoint,method:"POST",headers:{Authorization:`Bearer ${this.key}`,"Content-Type":"application/json","idempotency-key":"required-per-job"},body:JSON.stringify(preview.payload)});}}
export class MuApiClient{constructor(private transport:HttpTransport,private key?:string,private dryRun=true){} async submit(preview:Preview){if(this.dryRun)return {dryRun:true,preview};return this.transport.request({url:preview.endpoint,method:"POST",headers:{"x-api-key":this.key??"","Content-Type":"application/json"},body:JSON.stringify(preview.payload)});}}
export interface ProviderAssetPublisher{publish(asset:{id:string;url:string;kind:ReferenceKind}):Promise<{providerUrl:string;expiresAt?:string}>}
export class MockProviderAssetPublisher implements ProviderAssetPublisher{async publish(asset:{id:string;url:string}){return {providerUrl:`https://publisher.invalid/assets/${asset.id}`,expiresAt:"never"};}}
export const normalizeError=(type?:string)=>({authentication:"authentication",invalid_request_error:"validation",rate_limit_error:"rate_limited",insufficient_credits:"insufficient_balance",service_unavailable:"provider_unavailable",provider_error:"generation_failure"}[type??""]??"unknown_provider_error");
