import { randomUUID } from "node:crypto";
import { db } from "./db";
import type { AppSnapshot, Character, CharacterReference, CharacterReferenceMeta, Conversation, ConversationMemory, GenerationDraft, GenerationInput, GenerationJob, JobEvent, JobReference, MediaAsset, Message, MessageAttachment, ProviderCapabilities, UsageEntry } from "./domain";

const now = () => new Date().toISOString();
const bool = <T extends Record<string, unknown>>(row: T) => ({ ...row, favorite: Boolean(row.favorite), isReference: Boolean(row.isReference), unread: Boolean(row.unread) });
export class SqliteFlexRepository {
  characters() { return db.prepare("SELECT * FROM characters ORDER BY name").all().map(bool) as unknown as Character[]; }
  character(id: string) { return bool(db.prepare("SELECT * FROM characters WHERE id=?").get(id) as Record<string, unknown>) as unknown as Character; }
  updateCharacter(id:string, patch:Partial<Pick<Character,"name"|"handle"|"portraitUrl"|"description"|"personality"|"identityNotes"|"defaultsJson">>) { const current=this.character(id); const next={...current,...patch}; db.prepare("UPDATE characters SET name=?,handle=?,portraitUrl=?,description=?,personality=?,identityNotes=?,defaultsJson=? WHERE id=?").run(next.name,next.handle,next.portraitUrl,next.description,next.personality,next.identityNotes,next.defaultsJson,id); return this.character(id); }
  media() { return db.prepare("SELECT * FROM media ORDER BY createdAt DESC").all().map(bool) as unknown as MediaAsset[]; }
  mediaByCharacter(id: string) { return db.prepare("SELECT * FROM media WHERE characterId=? ORDER BY createdAt DESC").all(id).map(bool) as unknown as MediaAsset[]; }
  asset(id: string) { return bool(db.prepare("SELECT * FROM media WHERE id=?").get(id) as Record<string, unknown>) as unknown as MediaAsset; }
  jobs() { return db.prepare("SELECT * FROM jobs ORDER BY createdAt DESC").all() as unknown as GenerationJob[]; }
  job(id: string) { return db.prepare("SELECT * FROM jobs WHERE id=?").get(id) as unknown as GenerationJob; }
  saveJob(job: GenerationJob) { db.prepare("INSERT INTO jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(job.id,job.characterId,job.mode,job.prompt,job.status,job.providerId,job.settingsJson,job.parentMediaId,job.conversationId,job.createdAt,job.updatedAt,job.error,job.mediaId); }
  updateJob(id: string, patch: Partial<GenerationJob>) { const existing=this.job(id); const next={...existing,...patch,updatedAt:now()}; db.prepare("UPDATE jobs SET status=?,updatedAt=?,error=?,mediaId=? WHERE id=?").run(next.status,next.updatedAt,next.error,next.mediaId,id); return this.job(id); }
  saveMedia(media: MediaAsset) { db.prepare("INSERT INTO media VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(media.id,media.characterId,media.type,media.url,media.posterUrl,media.title,media.caption,media.prompt,media.providerId,media.settingsJson,media.parentId,Number(media.isReference),media.createdAt,Number(media.favorite)); }
  toggleFavorite(id: string) { db.prepare("UPDATE media SET favorite=CASE favorite WHEN 1 THEN 0 ELSE 1 END WHERE id=?").run(id); return this.asset(id); }
  setReference(id: string) { db.prepare("UPDATE media SET isReference=1 WHERE id=?").run(id); return this.asset(id); }
  addCharacterReference(characterId:string,mediaId:string,role:CharacterReference["role"]="face",canonical=true) { const createdAt=now(); db.prepare("INSERT INTO characterReferences VALUES(?,?,?,?,?) ON CONFLICT(characterId,mediaId,role) DO UPDATE SET canonical=excluded.canonical").run(characterId,mediaId,role,Number(canonical),createdAt); db.prepare("INSERT INTO characterReferenceMeta VALUES(?,?,?,?,?,?,?) ON CONFLICT(characterId,mediaId,role) DO NOTHING").run(characterId,mediaId,role,"","",1,0); }
  updateCharacterReference(characterId:string,mediaId:string,role:CharacterReference["role"],patch:Partial<Pick<CharacterReferenceMeta,"label"|"notes"|"active"|"priority"|"canonical">>) { const existing=this.characterReferences(characterId).find(x=>x.mediaId===mediaId&&x.role===role); if(!existing) throw new Error("Reference missing"); if(patch.canonical!==undefined) db.prepare("UPDATE characterReferences SET canonical=? WHERE characterId=? AND mediaId=? AND role=?").run(Number(patch.canonical),characterId,mediaId,role); const meta={...existing,...patch}; db.prepare("UPDATE characterReferenceMeta SET label=?,notes=?,active=?,priority=? WHERE characterId=? AND mediaId=? AND role=?").run(meta.label,meta.notes,Number(meta.active),meta.priority,characterId,mediaId,role); return this.characterReferences(characterId).find(x=>x.mediaId===mediaId&&x.role===role); }
  removeCharacterReference(characterId:string,mediaId:string,role:CharacterReference["role"]) { db.prepare("DELETE FROM characterReferences WHERE characterId=? AND mediaId=? AND role=?").run(characterId,mediaId,role); db.prepare("DELETE FROM characterReferenceMeta WHERE characterId=? AND mediaId=? AND role=?").run(characterId,mediaId,role); }
  characterReferences(characterId?:string) { const query=`SELECT r.*,COALESCE(m.label,'') as label,COALESCE(m.notes,'') as notes,COALESCE(m.active,1) as active,COALESCE(m.priority,0) as priority FROM characterReferences r LEFT JOIN characterReferenceMeta m ON r.characterId=m.characterId AND r.mediaId=m.mediaId AND r.role=m.role ${characterId?"WHERE r.characterId=?":""} ORDER BY priority DESC,r.createdAt`; return db.prepare(query).all(...(characterId?[characterId]:[])).map(row=>({...row as object,canonical:Boolean((row as {canonical:number}).canonical),active:Boolean((row as {active:number}).active)})) as CharacterReferenceMeta[]; }
  saveJobReferences(jobId:string, references: {mediaId:string;role:JobReference["role"]}[]) { for(const [position,item] of references.entries()) db.prepare("INSERT OR IGNORE INTO jobReferences VALUES(?,?,?,?)").run(jobId,item.mediaId,item.role,position); }
  jobReferences(jobId?:string) { const query=jobId?"SELECT * FROM jobReferences WHERE jobId=? ORDER BY position":"SELECT * FROM jobReferences ORDER BY jobId,position"; return db.prepare(query).all(...(jobId?[jobId]:[])) as unknown as JobReference[]; }
  setNote(id: string, body: string) { db.prepare("INSERT INTO notes(mediaId,body) VALUES(?,?) ON CONFLICT(mediaId) DO UPDATE SET body=excluded.body").run(id,body); }
  conversations() { return db.prepare("SELECT * FROM conversations ORDER BY updatedAt DESC").all().map(bool) as unknown as Conversation[]; }
  messages(conversationId: string) { return db.prepare("SELECT * FROM messages WHERE conversationId=? ORDER BY createdAt").all(conversationId) as unknown as Message[]; }
  conversationForCharacter(characterId: string) { return this.conversations().find(c=>c.characterId===characterId); }
  addMessage(conversationId: string, role: Message["role"], body: string) { const message={id:randomUUID(),conversationId,role,body,createdAt:now()}; db.prepare("INSERT INTO messages VALUES(?,?,?,?,?)").run(message.id,message.conversationId,message.role,message.body,message.createdAt); db.prepare("UPDATE conversations SET updatedAt=?,unread=? WHERE id=?").run(message.createdAt,role==="character"?1:0,conversationId); return message; }
  attachMessage(messageId:string,mediaId:string,kind:MessageAttachment["kind"]="media") { db.prepare("INSERT OR IGNORE INTO messageAttachments VALUES(?,?,?)").run(messageId,mediaId,kind); }
  memory(conversationId?:string) { const q=conversationId?"SELECT * FROM conversationMemory WHERE conversationId=?":"SELECT * FROM conversationMemory"; return db.prepare(q).all(...(conversationId?[conversationId]:[])) as unknown as ConversationMemory[]; }
  saveMemory(memory:ConversationMemory) { db.prepare("INSERT INTO conversationMemory VALUES(?,?,?,?,?) ON CONFLICT(conversationId) DO UPDATE SET summary=excluded.summary,pinnedFacts=excluded.pinnedFacts,contextNotes=excluded.contextNotes,updatedAt=excluded.updatedAt").run(memory.conversationId,memory.summary,memory.pinnedFacts,memory.contextNotes,memory.updatedAt); }
  saveDraft(draft:GenerationDraft) { db.prepare("INSERT INTO drafts VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET characterId=excluded.characterId,mode=excluded.mode,payloadJson=excluded.payloadJson,updatedAt=excluded.updatedAt").run(draft.id,draft.characterId,draft.mode,draft.payloadJson,draft.updatedAt); }
  draft(id="current") { return db.prepare("SELECT * FROM drafts WHERE id=?").get(id) as unknown as GenerationDraft; }
  clearDraft(id="current") { db.prepare("DELETE FROM drafts WHERE id=?").run(id); }
  addLedger(entry:UsageEntry) { db.prepare("INSERT OR IGNORE INTO usageLedger VALUES(?,?,?,?,?,?,?,?,?)").run(entry.id,entry.jobId,entry.providerId,entry.model,entry.mediaType,entry.estimatedCost,entry.actualCost,entry.usageJson,entry.createdAt); }
  ledger() { return db.prepare("SELECT * FROM usageLedger ORDER BY createdAt DESC").all() as unknown as UsageEntry[]; }
  addJobEvent(event:JobEvent) { db.prepare("INSERT INTO jobEvents VALUES(?,?,?,?,?,?)").run(event.id,event.jobId,event.channel,event.state,event.message,event.createdAt); }
  events(jobId?:string) { const q=jobId?"SELECT * FROM jobEvents WHERE jobId=? ORDER BY createdAt":"SELECT * FROM jobEvents ORDER BY createdAt DESC"; return db.prepare(q).all(...(jobId?[jobId]:[])) as unknown as JobEvent[]; }
  createCollection(name:string) { const id=randomUUID(); db.prepare("INSERT INTO collections VALUES(?,?)").run(id,name); return {id,name,mediaIds:[]}; }
  renameCollection(id:string,name:string) { db.prepare("UPDATE collections SET name=? WHERE id=?").run(name,id); }
  addToCollection(collectionId:string,mediaId:string) { db.prepare("INSERT OR IGNORE INTO collectionItems VALUES(?,?)").run(collectionId,mediaId); }
  removeFromCollection(collectionId:string,mediaId:string) { db.prepare("DELETE FROM collectionItems WHERE collectionId=? AND mediaId=?").run(collectionId,mediaId); }
  snapshot(capabilities:ProviderCapabilities[]=[]): AppSnapshot { const collections=db.prepare("SELECT * FROM collections ORDER BY name").all() as unknown as {id:string;name:string}[]; const notes=Object.fromEntries((db.prepare("SELECT * FROM notes").all() as unknown as {mediaId:string;body:string}[]).map(x=>[x.mediaId,x.body])); return {characters:this.characters(),media:this.media(),jobs:this.jobs(),conversations:this.conversations(),messages:(db.prepare("SELECT * FROM messages ORDER BY createdAt").all() as unknown as Message[]),collections:collections.map(c=>({...c,mediaIds:(db.prepare("SELECT mediaId FROM collectionItems WHERE collectionId=?").all(c.id) as unknown as {mediaId:string}[]).map(x=>x.mediaId)})),notes,characterReferences:this.characterReferences(),jobReferences:this.jobReferences(),capabilities,drafts:(db.prepare("SELECT * FROM drafts").all() as unknown as GenerationDraft[]),ledger:this.ledger(),memory:this.memory(),attachments:(db.prepare("SELECT * FROM messageAttachments").all() as unknown as MessageAttachment[]),events:this.events()}; }
  createJob(input: GenerationInput) { const createdAt=now(); const job:GenerationJob={id:randomUUID(),characterId:input.characterId,mode:input.mode,prompt:input.prompt,status:"queued",providerId:input.mode==="image"?"mock-image":"mock-video",settingsJson:JSON.stringify(input),parentMediaId:input.parentMediaId??null,conversationId:input.conversationId??null,createdAt,updatedAt:createdAt,error:null,mediaId:null}; this.saveJob(job); const references=[...(input.referenceAssetIds??[]).map(mediaId=>({mediaId,role:"scene" as const})),...(input.parentMediaId?[{mediaId:input.parentMediaId,role:"parent" as const}]:[])]; this.saveJobReferences(job.id,references); return job; }
}
export const repository = new SqliteFlexRepository();
