import { randomUUID } from "node:crypto";
import { db } from "./db";
import { emptyCharacterProfile, emptyCreativeMemory } from "./brain-defaults";
import type { AppSnapshot, Character, CharacterProfile, CharacterReference, CharacterReferenceMeta, ChatUsageEntry, Conversation, ConversationMemory, ConversationProviderDeployment, ConversationSummary, CreativeMemory, GenerationDraft, GenerationInput, GenerationJob, InitiativeState, JobEvent, JobReference, MediaAsset, MediaReaction, Message, MessageAttachment, PinnedMemory, ProposalReference, ProviderCapabilities, SceneProposal, SceneProposalStatus, UsageEntry } from "./domain";

const now = () => new Date().toISOString();
const parseJson = <T,>(value:string|undefined|null,fallback:T):T=>{try{return value?JSON.parse(value) as T:fallback;}catch{return fallback;}};
const bool = <T extends Record<string, unknown>>(row: T) => {
  const { archived, ...values } = row;
  return { ...values, ...(archived === undefined ? {} : { archived: Boolean(archived) }), favorite: Boolean(row.favorite), isReference: Boolean(row.isReference), unread: Boolean(row.unread) };
};
export class SqliteFlexRepository {
  characters() { return db.prepare("SELECT * FROM characters WHERE archived=0 ORDER BY name").all().map(bool) as unknown as Character[]; }
  character(id: string) { return bool(db.prepare("SELECT * FROM characters WHERE id=?").get(id) as Record<string, unknown>) as unknown as Character; }
  updateCharacter(id:string, patch:Partial<Pick<Character,"name"|"handle"|"portraitUrl"|"description"|"personality"|"identityNotes"|"defaultsJson">>) { const current=this.character(id); const next={...current,...patch}; db.prepare("UPDATE characters SET name=?,handle=?,portraitUrl=?,description=?,personality=?,identityNotes=?,defaultsJson=? WHERE id=?").run(next.name,next.handle,next.portraitUrl,next.description,next.personality,next.identityNotes,next.defaultsJson,id); return this.character(id); }
  archiveCharacter(id:string) { db.prepare("UPDATE characters SET archived=1 WHERE id=?").run(id); return this.character(id); }
  createCharacter(name:string, description="") { const existing=this.characters().find((item)=>item.name.trim().toLocaleLowerCase()===name.trim().toLocaleLowerCase()); if(existing)return existing; const id=randomUUID(),createdAt=now(); db.prepare("INSERT INTO characters(id,name,handle,portraitUrl,description,personality,identityNotes,defaultsJson,createdAt,archived) VALUES(?,?,?,?,?,?,?,?,?,0)").run(id,name.trim(),"","",description.trim(),"","","{}",createdAt); db.prepare("INSERT INTO conversations VALUES(?,?,?,?)").run(randomUUID(),id,createdAt,0); const profile=emptyCharacterProfile(id); this.saveCharacterProfile(profile); this.saveCreativeMemory(emptyCreativeMemory(id)); db.prepare("INSERT OR IGNORE INTO initiativeStates(characterId,cooldownSeconds,maxPerDay) VALUES(?,28800,1)").run(id); return this.character(id); }
  media() { return db.prepare("SELECT * FROM media ORDER BY createdAt DESC").all().map(bool) as unknown as MediaAsset[]; }
  mediaByCharacter(id: string) { return db.prepare("SELECT * FROM media WHERE characterId=? ORDER BY createdAt DESC").all(id).map(bool) as unknown as MediaAsset[]; }
  asset(id: string):MediaAsset|undefined { const row=db.prepare("SELECT * FROM media WHERE id=?").get(id) as Record<string,unknown>|undefined;return row?bool(row) as unknown as MediaAsset:undefined; }
  jobs() { return db.prepare("SELECT * FROM jobs ORDER BY createdAt DESC").all() as unknown as GenerationJob[]; }
  job(id: string) { return db.prepare("SELECT * FROM jobs WHERE id=?").get(id) as unknown as GenerationJob; }
  saveJob(job: GenerationJob) { db.prepare("INSERT INTO jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(job.id,job.characterId,job.mode,job.prompt,job.status,job.providerId,job.settingsJson,job.parentMediaId,job.conversationId,job.createdAt,job.updatedAt,job.error,job.mediaId); }
  updateJob(id: string, patch: Partial<GenerationJob>) { const existing=this.job(id); const next={...existing,...patch,updatedAt:now()}; db.prepare("UPDATE jobs SET status=?,updatedAt=?,error=?,mediaId=? WHERE id=?").run(next.status,next.updatedAt,next.error,next.mediaId,id); return this.job(id); }
  saveMedia(media: MediaAsset) { db.prepare("INSERT INTO media VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(media.id,media.characterId,media.type,media.url,media.posterUrl,media.title,media.caption,media.prompt,media.providerId,media.settingsJson,media.parentId,Number(media.isReference),media.createdAt,Number(media.favorite)); }
  saveMediaAsCharacterReference(media:MediaAsset, role:CharacterReference["role"], canonical=true) { db.exec("BEGIN IMMEDIATE"); try { this.saveMedia(media); this.addCharacterReference(media.characterId,media.id,role,canonical); db.prepare("UPDATE media SET isReference=1 WHERE id=?").run(media.id); db.exec("COMMIT"); } catch(error) { db.exec("ROLLBACK"); throw error; } }
  saveCharacterPortraitReference(media:MediaAsset) { if(media.type!=="image") throw new Error("Character portraits must be images."); db.exec("BEGIN IMMEDIATE"); try { this.saveMedia(media); this.addCharacterReference(media.characterId,media.id,"face",false); db.prepare("UPDATE media SET isReference=1 WHERE id=?").run(media.id); this.updateCharacter(media.characterId,{portraitUrl:media.url}); db.exec("COMMIT"); } catch(error) { db.exec("ROLLBACK"); throw error; } }
  toggleFavorite(id: string) { db.prepare("UPDATE media SET favorite=CASE favorite WHEN 1 THEN 0 ELSE 1 END WHERE id=?").run(id); return this.asset(id); }
  setReference(id: string) { db.prepare("UPDATE media SET isReference=1 WHERE id=?").run(id); return this.asset(id); }
  addCharacterReference(characterId:string,mediaId:string,role:CharacterReference["role"]="face",canonical=false) { const createdAt=now(); db.prepare("INSERT INTO characterReferences VALUES(?,?,?,?,?) ON CONFLICT(characterId,mediaId,role) DO UPDATE SET canonical=excluded.canonical").run(characterId,mediaId,role,Number(canonical),createdAt); db.prepare("INSERT INTO characterReferenceMeta VALUES(?,?,?,?,?,?,?) ON CONFLICT(characterId,mediaId,role) DO NOTHING").run(characterId,mediaId,role,"","",1,0); }
  updateCharacterReference(characterId:string,mediaId:string,role:CharacterReference["role"],patch:Partial<Pick<CharacterReferenceMeta,"label"|"notes"|"active"|"priority"|"canonical">>) { const existing=this.characterReferences(characterId).find(x=>x.mediaId===mediaId&&x.role===role); if(!existing) throw new Error("Reference missing"); if(patch.canonical!==undefined) db.prepare("UPDATE characterReferences SET canonical=? WHERE characterId=? AND mediaId=? AND role=?").run(Number(patch.canonical),characterId,mediaId,role); const meta={...existing,...patch}; db.prepare("UPDATE characterReferenceMeta SET label=?,notes=?,active=?,priority=? WHERE characterId=? AND mediaId=? AND role=?").run(meta.label,meta.notes,Number(meta.active),meta.priority,characterId,mediaId,role); return this.characterReferences(characterId).find(x=>x.mediaId===mediaId&&x.role===role); }
  removeCharacterReference(characterId:string,mediaId:string,role:CharacterReference["role"]) { db.prepare("DELETE FROM characterReferences WHERE characterId=? AND mediaId=? AND role=?").run(characterId,mediaId,role); db.prepare("DELETE FROM characterReferenceMeta WHERE characterId=? AND mediaId=? AND role=?").run(characterId,mediaId,role); }
  characterReferences(characterId?:string) { const query=`SELECT r.*,COALESCE(m.label,'') as label,COALESCE(m.notes,'') as notes,COALESCE(m.active,1) as active,COALESCE(m.priority,0) as priority FROM characterReferences r LEFT JOIN characterReferenceMeta m ON r.characterId=m.characterId AND r.mediaId=m.mediaId AND r.role=m.role ${characterId?"WHERE r.characterId=?":""} ORDER BY priority DESC,r.createdAt`; return db.prepare(query).all(...(characterId?[characterId]:[])).map(row=>({...row as object,canonical:Boolean((row as {canonical:number}).canonical),active:Boolean((row as {active:number}).active)})) as CharacterReferenceMeta[]; }
  saveJobReferences(jobId:string, references: {mediaId:string;role:JobReference["role"]}[]) { for(const [position,item] of references.entries()) db.prepare("INSERT OR IGNORE INTO jobReferences VALUES(?,?,?,?)").run(jobId,item.mediaId,item.role,position); }
  jobReferences(jobId?:string) { const query=jobId?"SELECT * FROM jobReferences WHERE jobId=? ORDER BY position":"SELECT * FROM jobReferences ORDER BY jobId,position"; return db.prepare(query).all(...(jobId?[jobId]:[])) as unknown as JobReference[]; }
  setNote(id: string, body: string) { db.prepare("INSERT INTO notes(mediaId,body) VALUES(?,?) ON CONFLICT(mediaId) DO UPDATE SET body=excluded.body").run(id,body); }
  conversations() { return db.prepare("SELECT * FROM conversations ORDER BY updatedAt DESC").all().map(bool) as unknown as Conversation[]; }
  messages(conversationId: string) { return db.prepare("SELECT * FROM messages WHERE conversationId=? ORDER BY createdAt").all(conversationId) as unknown as Message[]; }
  conversationForCharacter(characterId: string) { return this.conversations().find(c=>c.characterId===characterId); }
  addMessage(conversationId: string, role: Message["role"], body: string) { const message={id:randomUUID(),conversationId,role,body,createdAt:now()}; db.prepare("INSERT INTO messages VALUES(?,?,?,?,?)").run(message.id,message.conversationId,message.role,message.body,message.createdAt); db.prepare("UPDATE conversations SET updatedAt=?,unread=? WHERE id=?").run(message.createdAt,role==="character"?1:0,conversationId); return message; }
  attachMessage(messageId:string,mediaId:string,kind:MessageAttachment["kind"]="media") { db.prepare("INSERT OR IGNORE INTO messageAttachments VALUES(?,?,?)").run(messageId,mediaId,kind); }
  memory(conversationId?:string) { const q=conversationId?"SELECT * FROM conversationMemory WHERE conversationId=?":"SELECT * FROM conversationMemory"; return db.prepare(q).all(...(conversationId?[conversationId]:[])) as unknown as ConversationMemory[]; }
  saveMemory(memory:ConversationMemory) { db.prepare("INSERT INTO conversationMemory VALUES(?,?,?,?,?) ON CONFLICT(conversationId) DO UPDATE SET summary=excluded.summary,pinnedFacts=excluded.pinnedFacts,contextNotes=excluded.contextNotes,updatedAt=excluded.updatedAt").run(memory.conversationId,memory.summary,memory.pinnedFacts,memory.contextNotes,memory.updatedAt); }
  saveDraft(draft:GenerationDraft) { db.prepare("INSERT INTO drafts VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET characterId=excluded.characterId,mode=excluded.mode,payloadJson=excluded.payloadJson,updatedAt=excluded.updatedAt").run(draft.id,draft.characterId,draft.mode,draft.payloadJson,draft.updatedAt); }
  draft(id="current") { return db.prepare("SELECT * FROM drafts WHERE id=?").get(id) as unknown as GenerationDraft; }
  clearDraft(id="current") { db.prepare("DELETE FROM drafts WHERE id=?").run(id); }
  addLedger(entry:UsageEntry) { db.prepare("INSERT OR IGNORE INTO usageLedger VALUES(?,?,?,?,?,?,?,?,?)").run(entry.id,entry.jobId,entry.providerId,entry.model,entry.mediaType,entry.estimatedCost,entry.actualCost,entry.usageJson,entry.createdAt); }
  ledger() { return db.prepare("SELECT * FROM usageLedger ORDER BY createdAt DESC").all() as unknown as UsageEntry[]; }
  addJobEvent(event:JobEvent) { db.prepare("INSERT INTO jobEvents VALUES(?,?,?,?,?,?)").run(event.id,event.jobId,event.channel,event.state,event.message,event.createdAt); }
  events(jobId?:string) { const q=jobId?"SELECT * FROM jobEvents WHERE jobId=? ORDER BY createdAt":"SELECT * FROM jobEvents ORDER BY createdAt DESC"; return db.prepare(q).all(...(jobId?[jobId]:[])) as unknown as JobEvent[]; }
  characterProfiles() { return db.prepare("SELECT * FROM characterBrainProfiles ORDER BY characterId").all().map((row)=>{const r=row as Record<string,unknown>;const defaults=emptyCharacterProfile(String(r.characterId));return {characterId:String(r.characterId),initiativeLevel:String(r.initiativeLevel) as CharacterProfile["initiativeLevel"],adultCharacter:Boolean(r.adultCharacter),ageVerifiedAdult:Boolean(r.ageVerifiedAdult),conversationalProfile:{...defaults.conversationalProfile,...parseJson(String(r.conversationalProfileJson),{} as CharacterProfile["conversationalProfile"])},creativeProfile:{...defaults.creativeProfile,...parseJson(String(r.creativeProfileJson),{} as CharacterProfile["creativeProfile"])},updatedAt:String(r.updatedAt)};}) as CharacterProfile[]; }
  characterProfile(id:string) { return this.characterProfiles().find((item)=>item.characterId===id); }
  saveCharacterProfile(profile:CharacterProfile) { db.prepare("INSERT INTO characterBrainProfiles(characterId,initiativeLevel,adultCharacter,ageVerifiedAdult,conversationalProfileJson,creativeProfileJson,updatedAt) VALUES(?,?,?,?,?,?,?) ON CONFLICT(characterId) DO UPDATE SET initiativeLevel=excluded.initiativeLevel,adultCharacter=excluded.adultCharacter,ageVerifiedAdult=excluded.ageVerifiedAdult,conversationalProfileJson=excluded.conversationalProfileJson,creativeProfileJson=excluded.creativeProfileJson,updatedAt=excluded.updatedAt").run(profile.characterId,profile.initiativeLevel,Number(profile.adultCharacter),Number(profile.ageVerifiedAdult),JSON.stringify(profile.conversationalProfile),JSON.stringify(profile.creativeProfile),profile.updatedAt); return this.characterProfile(profile.characterId)!; }
  applyCharacterProfileDraft(characterId:string, characterPatch:Pick<Character,"description"|"personality"|"identityNotes">, profile:CharacterProfile) { db.exec("BEGIN IMMEDIATE"); try { this.updateCharacter(characterId,characterPatch); const saved=this.saveCharacterProfile({...profile,characterId,updatedAt:now()}); db.exec("COMMIT"); return {character:this.character(characterId),profile:saved}; } catch(error) { db.exec("ROLLBACK"); throw error; } }
  creativeMemories() { return db.prepare("SELECT * FROM creativeMemories").all().map((row)=>{const r=row as {characterId:string;payloadJson:string;updatedAt:string};return {...parseJson<CreativeMemory>(r.payloadJson,{} as CreativeMemory),characterId:r.characterId,updatedAt:r.updatedAt};}); }
  creativeMemory(id:string) { return this.creativeMemories().find((item)=>item.characterId===id); }
  saveCreativeMemory(memory:CreativeMemory) { db.prepare("INSERT INTO creativeMemories VALUES(?,?,?) ON CONFLICT(characterId) DO UPDATE SET payloadJson=excluded.payloadJson,updatedAt=excluded.updatedAt").run(memory.characterId,JSON.stringify(memory),memory.updatedAt); return this.creativeMemory(memory.characterId)!; }
  proposals(filters:{characterId?:string;conversationId?:string;status?:SceneProposalStatus[]}={}) { const where:string[]=[];const args:(string|number)[]=[];if(filters.characterId){where.push("characterId=?");args.push(filters.characterId);}if(filters.conversationId){where.push("conversationId=?");args.push(filters.conversationId);}if(filters.status?.length){where.push(`status IN (${filters.status.map(()=>"?").join(",")})`);args.push(...filters.status);}return db.prepare(`SELECT * FROM sceneProposals ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY updatedAt DESC`).all(...args).map((row)=>{const r=row as Record<string,unknown>;return {...r,id:String(r.id),parentProposalId:r.parentProposalId?String(r.parentProposalId):null,characterId:String(r.characterId),conversationId:String(r.conversationId),imageOrVideoIntent:String(r.imageOrVideoIntent) as SceneProposal["imageOrVideoIntent"],suggestedDuration:r.suggestedDuration===null?null:Number(r.suggestedDuration),suggestedReferenceIds:parseJson(String(r.suggestedReferenceIdsJson),[] as string[]),suggestedReferenceRoles:parseJson(String(r.suggestedReferenceRolesJson),{} as SceneProposal["suggestedReferenceRoles"]),sourceMessageIds:parseJson(String(r.sourceMessageIdsJson),[] as string[]),status:String(r.status) as SceneProposalStatus,proposalSource:String(r.proposalSource) as SceneProposal["proposalSource"],noveltyScore:Number(r.noveltyScore),similarityScore:Number(r.similarityScore),createdAt:String(r.createdAt),updatedAt:String(r.updatedAt)} as SceneProposal;}); }
  proposal(id:string) { return this.proposals().find((item)=>item.id===id); }
  saveProposal(proposal:SceneProposal) { db.prepare(`INSERT INTO sceneProposals(id,parentProposalId,characterId,conversationId,title,naturalLanguagePitch,concept,location,wardrobe,mood,lighting,shotDescription,cameraDirection,imageOrVideoIntent,suggestedAspectRatio,suggestedDuration,suggestedReferenceIdsJson,suggestedReferenceRolesJson,proposedImagePlan,proposedVideoPlan,noveltyReason,sourceMessageIdsJson,status,proposalSource,noveltyScore,similarityScore,createdAt,updatedAt) VALUES(${Array(28).fill("?").join(",")})`).run(proposal.id,proposal.parentProposalId,proposal.characterId,proposal.conversationId,proposal.title,proposal.naturalLanguagePitch,proposal.concept,proposal.location,proposal.wardrobe,proposal.mood,proposal.lighting,proposal.shotDescription,proposal.cameraDirection,proposal.imageOrVideoIntent,proposal.suggestedAspectRatio,proposal.suggestedDuration,JSON.stringify(proposal.suggestedReferenceIds),JSON.stringify(proposal.suggestedReferenceRoles),proposal.proposedImagePlan,proposal.proposedVideoPlan,proposal.noveltyReason,JSON.stringify(proposal.sourceMessageIds),proposal.status,proposal.proposalSource,proposal.noveltyScore,proposal.similarityScore,proposal.createdAt,proposal.updatedAt);this.saveProposalReferences(proposal.id,proposal.suggestedReferenceIds.map((mediaId,position)=>({proposalId:proposal.id,mediaId,role:proposal.suggestedReferenceRoles[mediaId]??"other",position})));return this.proposal(proposal.id)!; }
  updateProposal(id:string,status:SceneProposalStatus) { db.prepare("UPDATE sceneProposals SET status=?,updatedAt=? WHERE id=?").run(status,now(),id);return this.proposal(id); }
  updateProposalSources(id:string,sourceMessageIds:string[]) { db.prepare("UPDATE sceneProposals SET sourceMessageIdsJson=?,updatedAt=? WHERE id=?").run(JSON.stringify(sourceMessageIds),now(),id);return this.proposal(id); }
  saveProposalReferences(proposalId:string,refs:Omit<ProposalReference,"proposalId">[]) { db.prepare("DELETE FROM proposalReferences WHERE proposalId=?").run(proposalId);for(const ref of refs)db.prepare("INSERT OR IGNORE INTO proposalReferences VALUES(?,?,?,?)").run(proposalId,ref.mediaId,ref.role,ref.position); }
  proposalReferences(proposalId?:string) { return db.prepare(proposalId?"SELECT * FROM proposalReferences WHERE proposalId=? ORDER BY position":"SELECT * FROM proposalReferences ORDER BY proposalId,position").all(...(proposalId?[proposalId]:[])) as unknown as ProposalReference[]; }
  conversationSummaries() { return db.prepare("SELECT * FROM conversationSummaries").all().map((row)=>{const r=row as Record<string,unknown>;return {conversationId:String(r.conversationId),summary:String(r.summary),summarizedThroughMessageId:r.summarizedThroughMessageId?String(r.summarizedThroughMessageId):null,summarizedAt:r.summarizedAt?String(r.summarizedAt):null,pinnedFacts:parseJson(String(r.pinnedFactsJson),[] as string[]),recentUnsummarizedMessageIds:parseJson(String(r.recentUnsummarizedMessageIdsJson),[] as string[])};}) as ConversationSummary[]; }
  conversationSummary(id:string) { return this.conversationSummaries().find((item)=>item.conversationId===id); }
  saveConversationSummary(summary:ConversationSummary) { db.prepare("INSERT INTO conversationSummaries VALUES(?,?,?,?,?,?) ON CONFLICT(conversationId) DO UPDATE SET summary=excluded.summary,summarizedThroughMessageId=excluded.summarizedThroughMessageId,summarizedAt=excluded.summarizedAt,pinnedFactsJson=excluded.pinnedFactsJson,recentUnsummarizedMessageIdsJson=excluded.recentUnsummarizedMessageIdsJson").run(summary.conversationId,summary.summary,summary.summarizedThroughMessageId,summary.summarizedAt,JSON.stringify(summary.pinnedFacts),JSON.stringify(summary.recentUnsummarizedMessageIds));return this.conversationSummary(summary.conversationId)!; }
  pinnedMemories(conversationId?:string) { return db.prepare(conversationId?"SELECT * FROM pinnedMemories WHERE conversationId=? ORDER BY createdAt DESC":"SELECT * FROM pinnedMemories ORDER BY createdAt DESC").all(...(conversationId?[conversationId]:[])) as unknown as PinnedMemory[]; }
  addPinnedMemory(item:Omit<PinnedMemory,"id"|"createdAt">) { const memory={...item,id:randomUUID(),createdAt:now()};db.prepare("INSERT INTO pinnedMemories VALUES(?,?,?,?,?)").run(memory.id,memory.conversationId,memory.category,memory.body,memory.createdAt);return memory; }
  initiativeStates() { return db.prepare("SELECT * FROM initiativeStates").all().map((row)=>{const r=row as Record<string,unknown>;return {characterId:String(r.characterId),lastEvaluatedAt:r.lastEvaluatedAt?String(r.lastEvaluatedAt):null,nextEligibleAt:r.nextEligibleAt?String(r.nextEligibleAt):null,lastProactiveProposalAt:r.lastProactiveProposalAt?String(r.lastProactiveProposalAt):null,dailyCount:Number(r.dailyCount),dailyCountDate:r.dailyCountDate?String(r.dailyCountDate):null,cooldownSeconds:Number(r.cooldownSeconds),maxPerDay:Number(r.maxPerDay)};}) as InitiativeState[]; }
  initiativeState(id:string) { return this.initiativeStates().find((item)=>item.characterId===id); }
  saveInitiativeState(state:InitiativeState) { db.prepare("INSERT INTO initiativeStates VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(characterId) DO UPDATE SET lastEvaluatedAt=excluded.lastEvaluatedAt,nextEligibleAt=excluded.nextEligibleAt,lastProactiveProposalAt=excluded.lastProactiveProposalAt,dailyCount=excluded.dailyCount,dailyCountDate=excluded.dailyCountDate,cooldownSeconds=excluded.cooldownSeconds,maxPerDay=excluded.maxPerDay").run(state.characterId,state.lastEvaluatedAt,state.nextEligibleAt,state.lastProactiveProposalAt,state.dailyCount,state.dailyCountDate,state.cooldownSeconds,state.maxPerDay);return this.initiativeState(state.characterId)!; }
  conversationProviders() { return db.prepare("SELECT * FROM conversationProviderRegistry ORDER BY providerId").all().map((row)=>{const r=row as Record<string,unknown>;return {providerId:String(r.providerId),model:String(r.model),connected:Boolean(r.connected),...parseJson<Omit<ConversationProviderDeployment,"providerId"|"model"|"connected">>(String(r.capabilitiesJson),{} as Omit<ConversationProviderDeployment,"providerId"|"model"|"connected">)};}) as ConversationProviderDeployment[]; }
  saveConversationProvider(provider:ConversationProviderDeployment) { const {providerId,model,connected,...capabilities}=provider;db.prepare("INSERT INTO conversationProviderRegistry VALUES(?,?,?, ?,?) ON CONFLICT(providerId) DO UPDATE SET model=excluded.model,connected=excluded.connected,capabilitiesJson=excluded.capabilitiesJson,updatedAt=excluded.updatedAt").run(providerId,model,Number(connected),JSON.stringify(capabilities),now());return this.conversationProviders().find((item)=>item.providerId===providerId)!; }
  addChatUsage(entry:ChatUsageEntry) { db.prepare("INSERT INTO chatUsageLedger VALUES(?,?,?,?,?,?,?,?,?,?)").run(entry.id,entry.providerId,entry.model,entry.characterId,entry.conversationId,entry.inputTokens,entry.outputTokens,entry.estimatedCost,entry.actualCost,entry.createdAt); }
  chatUsage() { return db.prepare("SELECT * FROM chatUsageLedger ORDER BY createdAt DESC").all() as unknown as ChatUsageEntry[]; }
  saveMediaReaction(reaction:MediaReaction) { db.prepare("INSERT OR REPLACE INTO mediaReactions VALUES(?,?,?,?,?,?)").run(reaction.mediaId,reaction.proposalId,reaction.characterId,reaction.messageId,reaction.payloadJson,reaction.createdAt); }
  mediaReactions() { return db.prepare("SELECT * FROM mediaReactions ORDER BY createdAt DESC").all() as unknown as MediaReaction[]; }
  createCollection(name:string) { const id=randomUUID(); db.prepare("INSERT INTO collections VALUES(?,?)").run(id,name); return {id,name,mediaIds:[]}; }
  renameCollection(id:string,name:string) { db.prepare("UPDATE collections SET name=? WHERE id=?").run(name,id); }
  addToCollection(collectionId:string,mediaId:string) { db.prepare("INSERT OR IGNORE INTO collectionItems VALUES(?,?)").run(collectionId,mediaId); }
  removeFromCollection(collectionId:string,mediaId:string) { db.prepare("DELETE FROM collectionItems WHERE collectionId=? AND mediaId=?").run(collectionId,mediaId); }
  snapshot(capabilities:ProviderCapabilities[]=[]): AppSnapshot {
    const characters=this.characters(); const characterIds=new Set(characters.map((item)=>item.id));
    const media=this.media().filter((item)=>characterIds.has(item.characterId)); const mediaIds=new Set(media.map((item)=>item.id));
    const jobs=this.jobs().filter((item)=>characterIds.has(item.characterId)); const jobIds=new Set(jobs.map((item)=>item.id));
    const conversations=this.conversations().filter((item)=>characterIds.has(item.characterId)); const conversationIds=new Set(conversations.map((item)=>item.id));
    const messages=(db.prepare("SELECT * FROM messages ORDER BY createdAt").all() as unknown as Message[]).filter((item)=>conversationIds.has(item.conversationId)); const messageIds=new Set(messages.map((item)=>item.id));
    const collections=(db.prepare("SELECT * FROM collections ORDER BY name").all() as unknown as {id:string;name:string}[]).map((collection)=>({...collection,mediaIds:(db.prepare("SELECT mediaId FROM collectionItems WHERE collectionId=?").all(collection.id) as unknown as {mediaId:string}[]).map((row)=>row.mediaId).filter((id)=>mediaIds.has(id))}));
    const notes=Object.fromEntries((db.prepare("SELECT * FROM notes").all() as unknown as {mediaId:string;body:string}[]).filter((item)=>mediaIds.has(item.mediaId)).map((item)=>[item.mediaId,item.body]));
    const proposals=this.proposals().filter((item)=>characterIds.has(item.characterId)); const proposalIds=new Set(proposals.map((item)=>item.id));
    return {characters,media,jobs,conversations,messages,collections,notes,characterReferences:this.characterReferences().filter((item)=>characterIds.has(item.characterId)&&mediaIds.has(item.mediaId)),jobReferences:this.jobReferences().filter((item)=>jobIds.has(item.jobId)&&mediaIds.has(item.mediaId)),capabilities,drafts:(db.prepare("SELECT * FROM drafts").all() as unknown as GenerationDraft[]).filter((item)=>characterIds.has(item.characterId)),ledger:this.ledger().filter((item)=>jobIds.has(item.jobId)),memory:this.memory().filter((item)=>conversationIds.has(item.conversationId)),attachments:(db.prepare("SELECT * FROM messageAttachments").all() as unknown as MessageAttachment[]).filter((item)=>messageIds.has(item.messageId)&&mediaIds.has(item.mediaId)),events:this.events().filter((item)=>jobIds.has(item.jobId)),characterProfiles:this.characterProfiles().filter((item)=>characterIds.has(item.characterId)),creativeMemories:this.creativeMemories().filter((item)=>characterIds.has(item.characterId)),proposals,proposalReferences:this.proposalReferences().filter((item)=>proposalIds.has(item.proposalId)&&mediaIds.has(item.mediaId)),conversationSummaries:this.conversationSummaries().filter((item)=>conversationIds.has(item.conversationId)),pinnedMemories:this.pinnedMemories().filter((item)=>conversationIds.has(item.conversationId)),initiativeStates:this.initiativeStates().filter((item)=>characterIds.has(item.characterId)),conversationProviders:this.conversationProviders(),chatUsage:this.chatUsage().filter((item)=>characterIds.has(item.characterId)),mediaReactions:this.mediaReactions().filter((item)=>mediaIds.has(item.mediaId))};
  }
  createJob(input: GenerationInput) { const createdAt=now(); const job:GenerationJob={id:randomUUID(),characterId:input.characterId,mode:input.mode,prompt:input.prompt,status:"queued",providerId:input.mode==="image"?"mock-image":"mock-video",settingsJson:JSON.stringify(input),parentMediaId:input.parentMediaId??null,conversationId:input.conversationId??null,createdAt,updatedAt:createdAt,error:null,mediaId:null}; this.saveJob(job); const references=[...(input.referenceAssetIds??[]).map(mediaId=>({mediaId,role:"scene" as const})),...(input.parentMediaId?[{mediaId:input.parentMediaId,role:"parent" as const}]:[])]; this.saveJobReferences(job.id,references); return job; }
}
export const repository = new SqliteFlexRepository();
