import { randomUUID } from "node:crypto";
import type { GenerationInput, GenerationJob, MediaAsset } from "./domain";
import { MockImageProvider, MockVideoProvider, mockImageCapabilities, mockVideoCapabilities } from "./providers";
import { repository } from "./repository";
import { LocalMediaStore } from "./storage";
const store=new LocalMediaStore(); const imageProvider=new MockImageProvider(); const videoProvider=new MockVideoProvider();
export class GenerationService {
  capabilities(){ return [mockImageCapabilities,mockVideoCapabilities]; }
  validate(input:GenerationInput){const capability=this.capabilities().find(c=>c.mode===input.mode);if(!capability)return "No compatible provider is available.";if(!capability.aspectRatios.includes(input.aspectRatio))return "Selected aspect ratio is unsupported by this provider.";if(input.duration&&!capability.durations.includes(input.duration))return "Selected duration is unsupported by this provider.";const references=(input.referenceAssetIds??[]).map(id=>repository.asset(id));if(references.length>1&&!capability.multipleReferences)return "This provider accepts only one reference asset.";if(references.some(a=>a.type==="image")&&!capability.referenceImages)return "This provider does not accept image references.";if(references.some(a=>a.type==="video")&&!capability.referenceVideos)return "This provider does not accept video references.";return null;}
  create(input: GenerationInput) { const job=repository.createJob(input); repository.addJobEvent({id:randomUUID(),jobId:job.id,channel:"poll",state:"queued",message:"Accepted by normalized mock provider.",createdAt:new Date().toISOString()}); repository.addLedger({id:randomUUID(),jobId:job.id,providerId:job.providerId,model:job.providerId,mediaType:job.mode,estimatedCost:0,actualCost:null,usageJson:JSON.stringify({units:0}),createdAt:new Date().toISOString()}); return job; }
  advance(id: string): GenerationJob { const job=repository.job(id); if (!job || ["completed","failed","cancelled"].includes(job.status)) return job; const input=JSON.parse(job.settingsJson) as GenerationInput; const character=repository.character(job.characterId); const provider=job.mode==="image"?imageProvider:videoProvider; const state=provider.advance({job,character,input},Date.now()-Date.parse(job.createdAt)); if(state.state==="completed") { const asset=this.complete(job,character.name,input); const completed=repository.updateJob(id,{status:"completed",mediaId:asset.id,error:null}); repository.addJobEvent({id:randomUUID(),jobId:id,channel:"poll",state:"completed",message:state.statusMessage??"Mock provider completed.",createdAt:new Date().toISOString()}); if(job.conversationId){const message=repository.addMessage(job.conversationId,"character",`${character.name}: Your generated ${job.mode} is ready in this conversation.`);repository.attachMessage(message.id,asset.id,"generation");} return completed; } const next=repository.updateJob(id,{status:state.state,error:state.error??null}); repository.addJobEvent({id:randomUUID(),jobId:id,channel:"poll",state:next.status,message:state.statusMessage??state.error??"Mock provider update.",createdAt:new Date().toISOString()}); return next; }
  callbackComplete(id:string){ const job=repository.job(id); if(!job||["completed","failed","cancelled"].includes(job.status)) return job; const input=JSON.parse(job.settingsJson) as GenerationInput; const character=repository.character(job.characterId); const asset=this.complete(job,character.name,input); const completed=repository.updateJob(id,{status:"completed",mediaId:asset.id,error:null}); repository.addJobEvent({id:randomUUID(),jobId:id,channel:"callback",state:"completed",message:"Simulated callback completion received.",createdAt:new Date().toISOString()}); return completed; }
  cancel(id:string){ const job=repository.job(id); if(["completed","failed","cancelled"].includes(job.status)) return job; const cancelled=repository.updateJob(id,{status:"cancelled",error:"Cancelled by user."});repository.addJobEvent({id:randomUUID(),jobId:id,channel:"poll",state:"cancelled",message:"Cancelled by user.",createdAt:new Date().toISOString()});return cancelled; }
  retry(id:string){ const job=repository.job(id); if(job.status!=="failed") return job; const input=JSON.parse(job.settingsJson) as GenerationInput; return this.create({...input,simulation:"success"}); }
  private complete(job:GenerationJob,characterName:string,input:GenerationInput):MediaAsset { const id=randomUUID(); const colors=["#7c3aed","#c026d3","#db2777","#2563eb"]; const accent=colors[id.charCodeAt(0)%colors.length]; const url=store.writeMockVisual(id,characterName,accent,input.mode==="video"?"MOCK VIDEO PREVIEW":"MOCK IMAGE"); const asset:MediaAsset={id,characterId:job.characterId,type:job.mode,url,posterUrl:job.mode==="video"?url:null,title:input.prompt.slice(0,42)||"Untitled scene",caption:`Created with ${job.mode==="image"?"Mock Image Provider":"Mock Video Provider"}`,prompt:input.prompt,providerId:job.providerId,settingsJson:job.settingsJson,parentId:job.parentMediaId??null,isReference:false,createdAt:new Date().toISOString(),favorite:false}; repository.saveMedia(asset); return asset; }
}
export const generationService=new GenerationService();
export class MockConversationService { reply(character: {name:string;personality:string},text:string,recent:string[]=[]){ const tone=character.personality.split(".")[0].toLowerCase(); const echo=text.slice(0,80); const continuity=recent.length>2?" I’m carrying the thread from our recent direction.":""; return `${character.name}: ${tone}. I hear “${echo}.”${continuity} I saved that direction for our next scene.`; } }
export const conversationService=new MockConversationService();
